Num1 = int(input("กรุณาใส่ค่าตัวเลขตัวที่ 1 : "))
Num2 = int(input("กรุณาใส่ค่าตัวเลขตัวที่ 2 : "))
print(Num1," + ",Num2," = ",Num1+Num2)
print(Num1," - ",Num2," = ",Num1-Num2)
print(Num1," * ",Num2," = ",Num1*Num2)
print(Num1," / ",Num2," = ",int(Num1/Num2))